{% set name = "gpustat" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f69135080b2668b662822633312c2180002c10111597af9631bb02e042755b6c

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  entry_points:
    - gpustat = gpustat:main

requirements:
  host:
    - python
    - pip
    - pytest-runner
    - setuptools
  run:
    - python
    - nvidia-ml
    - psutil
    - blessings >=1.6
    - six >=1.7

test:
  imports:
    - gpustat
  commands:
    - gpustat --help

about:
  home: https://github.com/wookayin/gpustat
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'A simple command-line utility for querying and monitoring GPU status'
  doc_url: https://github.com/wookayin/gpustat
  dev_url: https://github.com/wookayin/gpustat

extra:
  recipe-maintainers:
    - hadim
