{% set name = "gpustat" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 581e8ff858c32c95a322bb8f03f1d9dc3d177b4ecb33ddcbed2c373c67f4e3f1

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - gpustat = gpustat:main

requirements:
  host:
    - python >=3.5
    - pip
    - pytest-runner
    - setuptools
  run:
    - python >=3.5
    - nvidia-ml-py
    - psutil
    - blessings >=1.6
    - six >=1.7

test:
  imports:
    - gpustat
  requires:
    - pytest
    - mockito
  commands:
    - gpustat --help
    - pytest --pyargs gpustat.test_gpustat

about:
  home: https://github.com/wookayin/gpustat
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A simple command-line utility for querying and monitoring GPU status
  doc_url: https://github.com/wookayin/gpustat
  dev_url: https://github.com/wookayin/gpustat

extra:
  recipe-maintainers:
    - hadim
