travis:
  secure:
    BINSTAR_TOKEN: OUewX2CQYXOlbDVj+ZC+EAnMSvkZwhIM1qjD5Hvv6mfDeDFyYSi6v2xDg3t1Xtf98jJUXXsygSxvmrO/n6oXa7wdbI10tXgIbIhj72U72d5DBaSwCL7P34vIxD0tcFOCaoo/kfMiTaNy3ihVZDEPVwfFdRxCBF3n1fdsR90dLUxgsusQ4sfwYgBUNWjWCcskJ8pn8tM+rvc6AJrBIXUmO9VOnvHag765GDndTQ+YssKlrFYRJ0FVLRWsDON3206Jzcl3dPBhm4LHd3S2zUHiPGew92i9czQPcChwt8ps50gE5JDVJQmL/qv3jy0OADRkDIOK9f2eM6ycPC7/KGbUvmsiKRoBgi2o1/ATnNUvNvxRnDWY1Wq6vBEz+WLxnwOaxHFOK4tRVJxjd2IvuAC2tJ6JbmIZq14AOQC5yZg0jLiK74LE1JbTH88lZG7Ez8UmbM0VhcIo7+Q50wjYMic3uc1E8XF59hVpK41vIk25sarwwExuOACL/Qt0h3YBYv1eMisXYEPTEsUcc2ZG6/Wjqqhm2syFQB8aDGDo+ADu8y5HMhw4/iFtAZWY5I5AORXIfQWKKjc1xELwE3CTexKWxpVn5T5tI+dSzwYk9bOUo2v/fXqGLr3Zm8DEfFl4EUJ//LUXk4lObek94hDcOl+m9tvLgW8JEYdDr3UUQITvF64=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
